import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { CSSProperties } from 'react';
import { ArrowUUpLeft, ArrowUUpRight, ArrowUp, ArrowDown, ArrowsClockwise, ArrowsOut, ArrowsHorizontal, ArrowsVertical, Check, CaretDown, Copy, Crop, Cursor, DownloadSimple, Eraser, Eye, EyeSlash, Eyedropper, FilePlus, FolderOpen, Hand, Image, Info, Stack, LockSimple, LockSimpleOpen, MagnifyingGlassMinus, MagnifyingGlassPlus, PaintBrush, Plus, Selection, SlidersHorizontal, SquareHalf, Trash, UploadSimple, X } from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react';
import { Viewport } from './viewport.ts';
import type { Editor } from './core/editor.ts';
import { BLENDS, LIMITS } from './core/model.ts';
import type { Layer, Tool } from './core/model.ts';
import { context } from './core/raster.ts';

const blendNames=['正常','正片叠底','滤色','叠加','柔光','变暗','变亮','颜色减淡'];
const tools:{id:Tool;name:string;key:string;icon:Icon}[]=[{id:'move',name:'移动与变换',key:'V',icon:Cursor},{id:'select',name:'矩形选区',key:'M',icon:Selection},{id:'crop',name:'裁切画布',key:'C',icon:Crop},{id:'brush',name:'画笔',key:'B',icon:PaintBrush},{id:'erase',name:'擦除与恢复',key:'E',icon:Eraser},{id:'mask',name:'重绘区域',key:'Q',icon:SquareHalf},{id:'eyedropper',name:'吸管',key:'I',icon:Eyedropper},{id:'hand',name:'平移',key:'H',icon:Hand}];
const rangeStyle=(value:number,min:number,max:number):CSSProperties=>({'--range-progress':`${Math.max(0,Math.min(100,(value-min)/(max-min)*100))}%`} as CSSProperties);
function ToolButton({icon:Icon,label,onClick,disabled=false,active=false,className=''}:{icon:Icon;label:string;onClick:()=>void;disabled?:boolean;active?:boolean;className?:string}){return <button className={`icon-button ${active?'active':''} ${className}`} title={label} aria-label={label} aria-pressed={active||undefined} onClick={onClick} disabled={disabled}><Icon size={19}/></button>;}
function Thumbnail({layer,editor}:{layer:Layer;editor:Editor}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=context(c);ctx.clearRect(0,0,72,72);const image=editor.raster.layer(layer),s=Math.min(72/image.width,72/image.height);ctx.drawImage(image,(72-image.width*s)/2,(72-image.height*s)/2,image.width*s,image.height*s);},[layer,editor]);return <canvas ref={ref} width={72} height={72} className="layer-thumb"/>;}
function NumberField({label,value,onChange,min,max,step=1,disabled=false}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;disabled?:boolean}){return <label className="number-field"><span>{label}</span><input aria-label={label} type="number" value={Number(value.toFixed(2))} min={min} max={max} step={step} disabled={disabled} onChange={e=>{if(e.target.value!=='')onChange(Number(e.target.value));}}/></label>;}
function Adjust({editor,label,property,min=-100,max=100}:{editor:Editor;label:string;property:'opacity'|'brightness'|'contrast'|'saturation';min?:number;max?:number}){const layer=editor.active!;const value=(editor.preview?.id===layer.id?editor.preview.patch[property]??layer[property]:layer[property])*100;return <label className="adjust-row"><span>{label}<output>{Math.round(value)}{property==='opacity'?'%':''}</output></span><input type="range" aria-label={label} min={min} max={max} step={1} value={value} style={rangeStyle(value,min,max)} disabled={layer.locked} onChange={e=>editor.previewPatch({[property]:+e.target.value/100})} onPointerUp={()=>editor.commitPreview()} onPointerCancel={()=>editor.commitPreview()} onKeyUp={()=>editor.commitPreview()} onBlur={()=>editor.commitPreview()}/></label>;}

export function App({editor:e}:{editor:Editor}){
  useSyncExternalStore(e.subscribe,e.snapshot);const [dialog,setDialog]=useState<'new'|'export'|'help'|null>(null),[format,setFormat]=useState('image/png'),[drop,setDrop]=useState(false),[dragLayer,setDragLayer]=useState<string|null>(null);
  const dialogRef=useRef<HTMLDialogElement>(null),fileRef=useRef<HTMLInputElement>(null),projectRef=useRef<HTMLInputElement>(null),host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),board=useRef<HTMLDivElement>(null),overlay=useRef<HTMLCanvasElement>(null);
  const run=(fn:()=>unknown)=>{try{const r=fn();if(r instanceof Promise)void r.catch(err=>e.error(err));}catch(err){e.error(err);}};
  const replaceOK=()=>!e.doc.layers.length||e.lastBackupRevision===e.store.revision||window.confirm('打开新工程会替换当前画布。继续前，建议先保存工程文件。是否继续？');
  const importFiles=(files:File[])=>run(async()=>{if(files.length===1&&/\.lightps$/i.test(files[0].name)){if(replaceOK())await e.openProject(files[0]);}else await e.importImages(files,files.map(f=>f.name));});
  useEffect(()=>{if(!host.current||!canvas.current||!board.current||!overlay.current)return;const v=new Viewport(host.current,canvas.current,board.current,overlay.current,e);return()=>v.dispose();},[e]);
  useEffect(()=>{if(dialog)dialogRef.current?.showModal();else dialogRef.current?.close();},[dialog]);
  useEffect(()=>{
    const paste=(event:ClipboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.closest('input,textarea,[contenteditable]'))return;const files=[...(event.clipboardData?.files??[])].filter(f=>f.type.startsWith('image/'));if(files.length){event.preventDefault();importFiles(files);}};
    const keys=(event:KeyboardEvent)=>{const editable=event.target instanceof HTMLElement&&event.target.closest('input,textarea,select,[contenteditable]');const key=event.key.toLowerCase(),cmd=event.metaKey||event.ctrlKey;if((editable&&!cmd)||dialog)return;
      if(key==='escape'){e.preview=null;e.selection=null;e.setTool('move');e.emit();return;}
      if(cmd){const actions:Record<string,()=>unknown>={z:()=>event.shiftKey?e.redo():e.undo(),y:()=>e.redo(),s:()=>e.saveProject(),o:()=>projectRef.current?.click(),'0':()=>e.view?.fit(),'1':()=>e.view?.zoomTo(1/devicePixelRatio),d:()=>e.setSelection(null),j:()=>e.selected&&e.execute([{type:'layer.duplicate',id:e.selected}],'复制图层'),enter:()=>setDialog('export')};if(actions[key]){event.preventDefault();run(actions[key]);}return;}
      const tool=tools.find(t=>t.key.toLowerCase()===key);if(tool){event.preventDefault();e.setTool(tool.id);}
      else if(key==='delete'||key==='backspace'){if(e.selected){event.preventDefault();run(()=>e.execute([{type:'layer.remove',id:e.selected!}],'删除图层'));}}
      else if(key==='['||key===']'){e.brush.radius=Math.max(1,Math.min(200,e.brush.radius+(key==='['?-4:4)));e.emit();}
      else if(key==='enter'&&e.tool==='crop')run(()=>e.crop());
      else if(key.startsWith('arrow')&&e.active){event.preventDefault();const amount=event.shiftKey?10:1;run(()=>e.patch({x:e.active!.x+(key==='arrowright'?amount:key==='arrowleft'?-amount:0),y:e.active!.y+(key==='arrowdown'?amount:key==='arrowup'?-amount:0)}));}
    };
    document.addEventListener('paste',paste);document.addEventListener('keydown',keys);return()=>{document.removeEventListener('paste',paste);document.removeEventListener('keydown',keys);};
  });
  const layer=e.active,busy=e.busy||!e.ready||e.store.busy,brushTool=['brush','erase','mask'].includes(e.tool);
  const status={loading:'正在恢复',saving:'正在保存…',saved:'已在此浏览器保存',error:'自动保存失败',disabled:'请下载工程备份'}[e.saveState];
  return <main className={`app ${drop?'is-dropping':''}`} onDragOver={event=>{if(event.dataTransfer.types.includes('Files')){event.preventDefault();setDrop(true);}}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDrop(false);}} onDrop={event=>{if(event.dataTransfer.files.length){event.preventDefault();setDrop(false);importFiles([...event.dataTransfer.files]);}}}>
    <header className="topbar">
      <div className="brand"><Stack weight="duotone" size={25}/><span>lite <b>ps</b></span></div>
      <div className="header-actions"><button onClick={()=>setDialog('new')} disabled={busy}><FilePlus size={17}/><span>新建</span></button><button onClick={()=>projectRef.current?.click()} disabled={busy}><FolderOpen size={17}/><span>打开</span></button><button onClick={()=>fileRef.current?.click()} disabled={busy}><Plus size={17}/><span>添加图片</span></button></div>
      <div className="header-spacer"/>{e.hostConnection&&<button className="connection-button" onClick={()=>e.hostConnection?.disconnect()} title={e.hostConnection.origin}>已连接 · 断开</button>}
      <button className="save-project" onClick={()=>run(()=>e.saveProject())} disabled={busy}><DownloadSimple size={17}/><span>保存工程</span></button>
      <button className="primary export-button" onClick={()=>setDialog('export')} disabled={busy}><UploadSimple size={17}/><span>导出</span></button>
    </header>
    <div className="contextbar">
      <div className="history-controls"><ToolButton icon={ArrowUUpLeft} label={`撤销${e.store.undoLabel?' · '+e.store.undoLabel:''} (⌘Z)`} onClick={()=>run(()=>e.undo())} disabled={!e.store.canUndo||busy}/><ToolButton icon={ArrowUUpRight} label="重做 (⌘⇧Z)" onClick={()=>run(()=>e.redo())} disabled={!e.store.canRedo||busy}/></div>
      <span className="tool-name">{tools.find(t=>t.id===e.tool)?.name}</span>
      {brushTool?<div className="brush-options"><label>大小 <input aria-label="笔刷半径" type="number" min={1} max={200} value={e.brush.radius} onChange={event=>{e.brush.radius=Math.max(1,Math.min(200,+event.target.value));e.emit();}}/><span>px</span></label><label>硬度 <input aria-label="笔刷硬度" type="range" min={0} max={100} value={e.brush.hardness*100} style={rangeStyle(e.brush.hardness*100,0,100)} onChange={event=>{e.brush.hardness=+event.target.value/100;e.emit();}}/></label>{e.tool==='brush'?<input type="color" aria-label="画笔颜色" value={e.brush.color} onChange={event=>{e.brush.color=event.target.value;e.emit();}}/>:<button className={e.brush.restore?'selected-option':''} onClick={()=>{e.brush.restore=!e.brush.restore;e.emit();}}>{e.tool==='erase'?'恢复擦除':'减去区域'}<span className="toggle-dot"/></button>}</div>:e.tool==='crop'?<div className="inline-options"><span>拖出范围，按 Enter 裁切</span><button disabled={!e.selection||busy} onClick={()=>run(()=>e.crop())}><Check size={15}/>应用裁切</button></div>:<span className="tool-hint">{e.tool==='move'?'拖动图层 · Shift 辅助变换':e.tool==='hand'?'拖动画布 · 按住空格临时平移':e.tool==='select'?'拖出选区，限制画笔和擦除范围':e.tool==='eyedropper'?'点击画布取色':''}</span>}
      <div className="header-spacer"/>{e.selection&&<button className="clear-selection" onClick={()=>e.setSelection(null)}><X size={14}/>取消选区</button>}
    </div>
    <div className="workspace">
      <nav className="tools" aria-label="编辑工具">{tools.map(t=><ToolButton key={t.id} icon={t.icon} label={`${t.name} (${t.key})`} active={e.tool===t.id} disabled={busy} onClick={()=>e.setTool(t.id)}/>)}<div className="tool-divider"/><label className="color-chip" title="前景色"><input type="color" aria-label="前景色" value={e.brush.color} onChange={event=>{e.brush.color=event.target.value;e.emit();}}/></label><div className="tools-spacer"/><ToolButton icon={Info} label="使用帮助" onClick={()=>setDialog('help')}/></nav>
      <section className="canvas-area" aria-label="编辑画布">
        <div className="document-tab"><span className="document-dot"/><input aria-label="工程名称" key={e.doc.id} defaultValue={e.doc.name} onBlur={event=>{const name=event.target.value.trim().slice(0,100)||'未命名';run(()=>e.execute([{type:'document.rename',name}],'工程名称'));}}/><span>{e.doc.width} × {e.doc.height}</span><span className="save-state" data-state={e.saveState}>{e.saveState==='saved'&&<Check size={12}/>} {status}</span></div>
        <div className="viewport" ref={host}><div className="artboard" ref={board}/><canvas ref={canvas} aria-label="图层编辑画布"/><canvas className="overlay" ref={overlay}/>
          {!e.doc.layers.length&&e.ready&&<div className="empty-state"><div className="empty-icon"><Image size={32} weight="thin"/></div><h1>把图片放进来，开始编辑</h1><p>拖入图片，或直接粘贴</p><button className="empty-import" onClick={()=>fileRef.current?.click()}><Plus size={17}/>选择图片</button><button className="text-button" onClick={()=>run(()=>e.example())}>用示例试一试 <span>↗</span></button><small>PNG、JPEG、WebP · 图片在本机处理</small></div>}
        </div>
        <footer className="canvas-status"><span>{e.selection?`选区 ${Math.round(e.selection.width)} × ${Math.round(e.selection.height)}`:`${e.doc.layers.length} 个图层`}</span><span className="status-hint">{e.tool==='mask'?'红色区域参与重绘，导出为黑白遮罩':'空格拖动 · ⌘ / Ctrl + 滚轮缩放'}</span><div className="zoom-controls"><ToolButton icon={MagnifyingGlassMinus} label="缩小" onClick={()=>e.view?.zoomTo(e.zoom/1.25)}/><button className="zoom-value" onClick={()=>e.view?.zoomTo(1/devicePixelRatio)} title="100% 物理像素">{Math.round(e.zoom*devicePixelRatio*100)}%</button><ToolButton icon={MagnifyingGlassPlus} label="放大" onClick={()=>e.view?.zoomTo(e.zoom*1.25)}/><ToolButton icon={ArrowsOut} label="适合窗口 (⌘0)" onClick={()=>e.view?.fit()}/></div></footer>
      </section>
      <aside className="inspector" aria-label="图层和属性">
        <section className="layers-section"><div className="section-title"><h2>图层 <span>{e.doc.layers.length}</span></h2><div><ToolButton icon={Plus} label="添加空白图层" onClick={()=>run(()=>e.addBlank())} disabled={busy}/><ToolButton icon={Trash} label="删除图层" onClick={()=>run(()=>e.selected&&e.execute([{type:'layer.remove',id:e.selected}],'删除图层'))} disabled={!layer||layer.locked||busy}/></div></div>
          <div className="blend-controls"><select aria-label="混合模式" disabled={!layer||layer.locked||busy} value={layer?.blend??'source-over'} onChange={event=>run(()=>e.patch({blend:event.target.value as Layer['blend']}))}>{BLENDS.map((b,i)=><option value={b} key={b}>{blendNames[i]}</option>)}</select>{layer?<Adjust editor={e} label="不透明度" property="opacity" min={0}/>:<span className="muted">100%</span>}</div>
          <div className="layer-list" role="list" aria-label="图层列表">{[...e.doc.layers].reverse().map(l=><div key={l.id} role="listitem" className={`layer-row ${e.selected===l.id?'selected':''} ${!l.visible?'hidden-layer':''}`} draggable={!l.locked&&!busy} onDragStart={event=>{setDragLayer(l.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',l.id);}} onDragOver={event=>{if(dragLayer){event.preventDefault();event.currentTarget.classList.add('drop-target');}}} onDragLeave={event=>event.currentTarget.classList.remove('drop-target')} onDrop={event=>{event.preventDefault();event.currentTarget.classList.remove('drop-target');if(dragLayer)run(()=>e.execute([{type:'layer.reorder',id:dragLayer,index:e.doc.layers.indexOf(l)}],'排列图层'));setDragLayer(null);}} onDragEnd={()=>setDragLayer(null)}>
            <ToolButton icon={l.visible?Eye:EyeSlash} label={`${l.visible?'隐藏':'显示'} ${l.name}`} disabled={l.locked||busy} onClick={()=>run(()=>e.execute([{type:'layer.patch',id:l.id,patch:{visible:!l.visible}}],'图层显隐'))}/><button className="layer-select" onClick={()=>e.select(l.id)}><Thumbnail layer={l} editor={e}/><span>{l.name}<small>{l.assetId?'图片':'画布'}{l.mask.length?' · 蒙版':''}</small></span></button><ToolButton icon={l.locked?LockSimple:LockSimpleOpen} label={`${l.locked?'解锁':'锁定'} ${l.name}`} disabled={busy} className={l.locked?'is-locked':'layer-lock'} onClick={()=>run(()=>e.execute([{type:'layer.patch',id:l.id,patch:{locked:!l.locked}}],'图层锁定'))}/>
          </div>)}{!e.doc.layers.length&&<div className="no-layers"><Stack size={26} weight="thin"/><p>添加图片后，图层会出现在这里</p></div>}</div>
          <div className="layer-footer"><span>拖动调整顺序</span><ToolButton icon={ArrowUp} label="图层上移" disabled={!layer||layer.locked||busy||e.doc.layers.at(-1)===layer} onClick={()=>run(()=>layer&&e.execute([{type:'layer.reorder',id:layer.id,index:e.doc.layers.indexOf(layer)+1}],'图层上移'))}/><ToolButton icon={ArrowDown} label="图层下移" disabled={!layer||layer.locked||busy||e.doc.layers[0]===layer} onClick={()=>run(()=>layer&&e.execute([{type:'layer.reorder',id:layer.id,index:e.doc.layers.indexOf(layer)-1}],'图层下移'))}/><ToolButton icon={Copy} label="复制图层 (⌘J)" disabled={!layer||layer.locked||busy} onClick={()=>run(()=>layer&&e.execute([{type:'layer.duplicate',id:layer.id}],'复制图层'))}/></div>
        </section>
        <section className="properties"><div className="section-title"><h2><SlidersHorizontal size={15}/>属性</h2>{layer?.locked&&<span className="lock-note"><LockSimple size={12}/>已锁定</span>}</div>{layer?<fieldset disabled={layer.locked||busy}>
          <label className="rename-field"><span>名称</span><input aria-label="图层名称" key={layer.id+layer.name} defaultValue={layer.name} onBlur={event=>run(()=>e.patch({name:event.target.value.trim().slice(0,100)||'图层'}))}/></label>
          <h3>变换</h3><div className="number-grid"><NumberField label="X" value={layer.x} onChange={x=>run(()=>e.patch({x}))}/><NumberField label="Y" value={layer.y} onChange={y=>run(()=>e.patch({y}))}/><NumberField label="宽" value={layer.width*layer.scaleX} min={1} onChange={v=>run(()=>e.patch({scaleX:v/layer.width}))}/><NumberField label="高" value={layer.height*layer.scaleY} min={1} onChange={v=>run(()=>e.patch({scaleY:v/layer.height}))}/></div><div className="rotation-row"><NumberField label="角度" value={layer.rotation} onChange={rotation=>run(()=>e.patch({rotation}))}/><ToolButton icon={ArrowsHorizontal} label="水平翻转" active={layer.flipX} onClick={()=>run(()=>e.patch({flipX:!layer.flipX}))}/><ToolButton icon={ArrowsVertical} label="垂直翻转" active={layer.flipY} onClick={()=>run(()=>e.patch({flipY:!layer.flipY}))}/></div>
          <div className="adjust-title"><h3>色彩调整</h3><button onClick={()=>run(()=>e.patch({brightness:0,contrast:0,saturation:0}))} title="重置色彩调整"><ArrowsClockwise size={13}/>重置</button></div><Adjust editor={e} label="亮度" property="brightness"/><Adjust editor={e} label="对比度" property="contrast"/><Adjust editor={e} label="饱和度" property="saturation"/>
        </fieldset>:<div className="property-empty"><Cursor size={22} weight="thin"/><p>选择一个图层<br/>查看与调整它的属性</p></div>}
          {e.tool==='mask'&&<div className="mask-card"><strong><SquareHalf size={15}/>重绘区域</strong><p>红色标记需要重新生成的位置。它不会出现在合成图片中。</p><button disabled={!e.doc.inpaint.length||busy} onClick={()=>run(()=>e.execute([{type:'mask.clear'}],'清空重绘区域'))}>清空区域</button><button disabled={busy} onClick={()=>run(()=>e.downloadImage('image/png',true))}>导出遮罩</button></div>}
        </section>
        <div className="local-note"><span className="local-dot"/>在浏览器本地处理 <span>v0.1</span></div>
      </aside>
    </div>
    {drop&&<div className="drop-zone"><UploadSimple size={42}/><p>松开以添加图片或打开工程</p></div>}
    {e.hostRequest&&<div className="connection-request" role="alert"><strong>允许连接当前工程？</strong><p>{e.hostRequest.origin}</p><span>连接后，对方可以读取图片、修改图层并导出结果。</span><div><button onClick={()=>e.hostRequest?.reject()}>拒绝</button><button className="primary" onClick={()=>e.hostRequest?.accept()}>允许连接</button></div></div>}
    {e.message&&<div className={`toast ${e.messageKind}`} role={e.messageKind==='error'?'alert':'status'}>{e.messageKind==='error'?<Info size={17}/>:<Check size={17}/>}<span>{e.message}</span><button aria-label="关闭通知" onClick={()=>{e.message='';e.emit();}}><X size={15}/></button></div>}
    {e.busy&&<div className="busy-indicator" role="status"><span/>正在处理…</div>}
    <input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={event=>{importFiles([...event.target.files??[]]);event.target.value='';}}/>
    <input ref={projectRef} hidden type="file" accept=".lightps" onChange={event=>{if(event.target.files?.[0])importFiles([event.target.files[0]]);event.target.value='';}}/>
    <dialog ref={dialogRef} onCancel={()=>setDialog(null)} onClick={event=>{if(event.target===dialogRef.current)setDialog(null);}}>
      <div className="dialog-content"><div className="dialog-heading"><h2>{dialog==='new'?'新建画布':dialog==='export'?'导出图片':'随手编辑，轻松带走'}</h2><ToolButton icon={X} label="关闭对话框" onClick={()=>setDialog(null)}/></div>
      {dialog==='new'&&<form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(replaceOK())run(()=>{e.newDocument(+data.get('width')!,+data.get('height')!,String(data.get('name')||'未命名'));setDialog(null);});}}><label className="form-label">工程名称<input name="name" defaultValue="未命名" maxLength={100} autoFocus/></label><div className="form-grid"><label className="form-label">宽度 · px<input name="width" type="number" min={1} max={LIMITS.side} defaultValue={1600} required/></label><label className="form-label">高度 · px<input name="height" type="number" min={1} max={LIMITS.side} defaultValue={1200} required/></label></div><p className="dialog-note">透明背景 · 最大 4096 × 4096 像素</p><button className="primary dialog-primary" type="submit">创建画布</button></form>}
      {dialog==='export'&&<div><p className="export-dimensions">{e.doc.width} × {e.doc.height}<span>原始画布尺寸</span></p><label className="form-label">图片格式<select value={format} onChange={event=>setFormat(event.target.value)}><option value="image/png">PNG · 保留透明背景</option><option value="image/jpeg">JPEG · 白色背景</option><option value="image/webp">WebP · 更小的文件</option></select></label><button className="primary dialog-primary" onClick={()=>run(async()=>{await e.downloadImage(format);setDialog(null);})}><DownloadSimple size={17}/>下载图片</button><div className="export-secondary"><button onClick={()=>run(()=>e.copyImage())}><Copy size={16}/>复制图片</button><button onClick={()=>run(()=>e.downloadImage('image/png',true))}><SquareHalf size={16}/>下载黑白遮罩</button></div><p className="dialog-note">保留图层以便下次修改，请使用“保存工程”。</p></div>}
      {dialog==='help'&&<div className="help-content"><p>拖入、粘贴或添加图片。每张图片作为独立图层，所有处理都在当前浏览器完成。</p><dl><dt>移动 / 缩放 / 旋转</dt><dd>V · 拖动图层与控制点</dd><dt>平移 / 缩放视口</dt><dd>空格拖动 · ⌘ / Ctrl + 滚轮</dd><dt>撤销 / 重做</dt><dd>⌘Z / ⌘⇧Z（Windows 使用 Ctrl）</dd><dt>适合窗口 / 原始像素</dt><dd>⌘0 / ⌘1</dd><dt>画笔 / 擦除 / 重绘区域</dt><dd>B / E / Q · [ ] 调笔刷大小</dd><dt>保存工程 / 导出图片</dt><dd>⌘S / ⌘Enter</dd></dl><p>擦除可切换为“恢复擦除”。自动保存仅保存在此浏览器，请下载 .lightps 工程作为备份。</p><p className="dialog-note">首版支持基础位图编辑；暂不支持 PSD、文字排版及专用平台插件。</p></div>}
      </div>
    </dialog>
  </main>;
}
