import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { ArrowUUpLeft, ArrowUUpRight, ArrowUp, ArrowDown, ArrowsClockwise, ArrowsOut, ArrowsHorizontal, ArrowsVertical, Check, Circle, Copy, Crop, Cursor, DownloadSimple, Eraser, Eye, EyeSlash, Eyedropper, FilePlus, FolderMinus, FolderOpen, FolderPlus, Hand, Image, Info, Stack, LockSimple, LockSimpleOpen, MagicWand, MagnifyingGlassMinus, MagnifyingGlassPlus, PaintBrush, PaintBucket, Path, Plus, Selection, SlidersHorizontal, Trash, UploadSimple, X } from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react';
import { Viewport } from './viewport.ts';
import type { Editor } from './core/editor.ts';
import { BLENDS, GROUP_BLEND, LIMITS, isGroup, isRaster, locateNode, nodeCount } from './core/model.ts';
import { selectionBounds } from './core/selection.ts';
import type { GroupBlend, Layer, RasterLayer, Tool } from './core/model.ts';
import { context } from './core/raster.ts';
import { RangeSlider } from './components/motion/range-slider.tsx';

const blendNames=['正常','正片叠底','滤色','叠加','柔光','变暗','变亮','颜色减淡'];
const tools:{id:Tool;name:string;key:string;icon:Icon}[]=[{id:'move',name:'移动与变换',key:'V',icon:Cursor},{id:'select',name:'矩形选区',key:'M',icon:Selection},{id:'lasso',name:'套索',key:'L',icon:Path},{id:'wand',name:'魔棒',key:'W',icon:MagicWand},{id:'fill',name:'油漆桶',key:'G',icon:PaintBucket},{id:'crop',name:'裁切画布',key:'C',icon:Crop},{id:'brush',name:'画笔',key:'B',icon:PaintBrush},{id:'erase',name:'擦除与恢复',key:'E',icon:Eraser},{id:'eyedropper',name:'吸管',key:'I',icon:Eyedropper},{id:'hand',name:'平移',key:'H',icon:Hand}];
function ToolButton({icon:Icon,label,onClick,disabled=false,active=false,className=''}:{icon:Icon;label:string;onClick:()=>void;disabled?:boolean;active?:boolean;className?:string}){return <button className={`icon-button ${active?'active':''} ${className}`} title={label} aria-label={label} aria-pressed={active||undefined} onClick={onClick} disabled={disabled}><Icon size={19}/></button>;}
function Thumbnail({layer,editor}:{layer:RasterLayer;editor:Editor}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=context(c);ctx.clearRect(0,0,72,72);const image=editor.raster.pixels(layer),s=Math.min(72/image.width,72/image.height);ctx.drawImage(image,(72-image.width*s)/2,(72-image.height*s)/2,image.width*s,image.height*s);},[layer,editor]);return <canvas ref={ref} width={72} height={72} className="layer-thumb"/>;}
function MaskThumb({layer,editor}:{layer:Layer;editor:Editor}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c||!layer.mask)return;const ctx=context(c);ctx.clearRect(0,0,72,72);const w=isRaster(layer)?layer.width:editor.doc.width,h=isRaster(layer)?layer.height:editor.doc.height,image=editor.raster.maskImage(layer.mask,w,h),s=Math.min(72/image.width,72/image.height);ctx.drawImage(image,(72-image.width*s)/2,(72-image.height*s)/2,image.width*s,image.height*s);},[layer,editor]);return <canvas ref={ref} width={72} height={72} className="layer-thumb mask-thumb"/>;}
function NumberField({label,value,onChange,min,max,step=1,disabled=false}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;disabled?:boolean}){return <label className="number-field"><span>{label}</span><input aria-label={label} type="number" value={Number(value.toFixed(2))} min={min} max={max} step={step} disabled={disabled} onChange={e=>{if(e.target.value!=='')onChange(Number(e.target.value));}}/></label>;}
function Adjust({editor,label,property,min=-100,max=100}:{editor:Editor;label:string;property:'opacity'|'brightness'|'contrast'|'saturation';min?:number;max?:number}){
  const layer=editor.active;if(!layer)return null;if(property!=='opacity'&&!isRaster(layer))return null;
  const current=property==='opacity'?layer.opacity:(layer as RasterLayer)[property];
  const value=(editor.preview?.id===layer.id?editor.preview.patch[property]??current:current)*100;
  return <label className="adjust-row"><span>{label}<output>{Math.round(value)}{property==='opacity'?'%':''}</output></span><RangeSlider className="be-slider h-8" aria-label={label} min={min} max={max} step={1} value={value} showTicks={false} disabled={layer.locked} formatValueText={n=>property==='opacity'?`${Math.round(n)}%`:`${Math.round(n)}`} onValueChange={next=>editor.previewPatch({[property]:next/100})} onDragEnd={()=>editor.commitPreview()}/></label>;
}
function LayerTree({nodes,parentId,depth,e,busy,dragLayer,setDragLayer,run}:{nodes:Layer[];parentId:string|null;depth:number;e:Editor;busy:boolean;dragLayer:string|null;setDragLayer:(id:string|null)=>void;run:(fn:()=>unknown)=>void}){
  return <>{[...nodes].reverse().map(l=>{
    const emptyGroup=isGroup(l)&&!l.children.length;
    return <div key={l.id}>
      <div role="listitem" className={`layer-row ${e.selected===l.id?'selected':''} ${!l.visible?'hidden-layer':''}`} style={{paddingLeft:4+depth*16}} draggable={!l.locked&&!busy} onDragStart={event=>{setDragLayer(l.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',l.id);}} onDragOver={event=>{if(dragLayer&&dragLayer!==l.id){event.preventDefault();event.currentTarget.classList.add('drop-target');}}} onDragLeave={event=>event.currentTarget.classList.remove('drop-target')} onDrop={event=>{event.preventDefault();event.currentTarget.classList.remove('drop-target');if(dragLayer&&dragLayer!==l.id)run(()=>emptyGroup?e.execute([{type:'layer.reorder',id:dragLayer,index:0,parentId:l.id}],'移入组'):e.execute([{type:'layer.reorder',id:dragLayer,index:nodes.indexOf(l),parentId}],'排列图层'));setDragLayer(null);}} onDragEnd={()=>setDragLayer(null)}>
        <ToolButton icon={l.visible?Eye:EyeSlash} label={`${l.visible?'隐藏':'显示'} ${l.name}`} disabled={l.locked||busy} onClick={()=>run(()=>e.execute([{type:'layer.patch',id:l.id,patch:{visible:!l.visible}}],'图层显隐'))}/>
        <button className={`layer-channel ${e.selected===l.id&&!e.editingMask?'channel-on':''}`} title={l.name} onClick={()=>e.select(l.id,false)}>{isRaster(l)?<Thumbnail layer={l} editor={e}/>:<span className="layer-thumb layer-group-thumb"><Stack size={16} weight="thin"/></span>}</button>
        {l.mask&&<button className={`layer-channel ${e.selected===l.id&&e.editingMask?'channel-on':''} ${l.mask.disabled?'mask-off':''}`} title={`${l.name} 的图层蒙版`} onClick={event=>{if(event.altKey){e.select(l.id,true);e.viewMask=!e.viewMask;e.emit();return;}if(event.shiftKey){run(()=>e.disableMask(!l.mask!.disabled));return;}e.select(l.id,true);}}><MaskThumb layer={l} editor={e}/></button>}
        <button className="layer-select" onClick={()=>e.select(l.id,e.selected===l.id&&e.editingMask)}><span>{l.name}<small>{isGroup(l)?`组${l.blend===GROUP_BLEND?' · 穿透':''}`:isRaster(l)&&l.assetId?'图片':'画布'}{l.mask?l.mask.disabled?' · 蒙版已停用':' · 蒙版':''}</small></span></button>
        <ToolButton icon={l.locked?LockSimple:LockSimpleOpen} label={`${l.locked?'解锁':'锁定'} ${l.name}`} disabled={busy} className={l.locked?'is-locked':'layer-lock'} onClick={()=>run(()=>e.execute([{type:'layer.patch',id:l.id,patch:{locked:!l.locked}}],'图层锁定'))}/>
      </div>
      {isGroup(l)&&<LayerTree nodes={l.children} parentId={l.id} depth={depth+1} e={e} busy={busy} dragLayer={dragLayer} setDragLayer={setDragLayer} run={run}/>}
    </div>;
  })}</>;
}

export function App({editor:e}:{editor:Editor}){
  useSyncExternalStore(e.subscribe,e.snapshot);const [dialog,setDialog]=useState<'new'|'export'|'help'|null>(null),[format,setFormat]=useState('image/png'),[drop,setDrop]=useState(false),[dragLayer,setDragLayer]=useState<string|null>(null);
  const dialogRef=useRef<HTMLDialogElement>(null),fileRef=useRef<HTMLInputElement>(null),projectRef=useRef<HTMLInputElement>(null),host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),board=useRef<HTMLDivElement>(null),overlay=useRef<HTMLCanvasElement>(null);
  const run=(fn:()=>unknown)=>{try{const r=fn();if(r instanceof Promise)void r.catch(err=>e.error(err));}catch(err){e.error(err);}};
  const replaceOK=()=>!e.doc.layers.length||e.lastBackupRevision===e.store.revision||window.confirm('打开新工程会替换当前画布。继续前，建议先保存工程文件。是否继续？');
  const importFiles=(files:File[])=>run(async()=>{if(files.length===1&&/\.lightps$/i.test(files[0].name)){if(replaceOK())await e.openProject(files[0]);}else await e.importImages(files,files.map(f=>f.name));});
  useEffect(()=>{if(!host.current||!canvas.current||!board.current||!overlay.current)return;const v=new Viewport(host.current,canvas.current,board.current,overlay.current,e);return()=>v.dispose();},[e]);
  useEffect(()=>{if(dialog)dialogRef.current?.showModal();else dialogRef.current?.close();},[dialog]);
  useEffect(()=>{
    const paste=(event:ClipboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.closest('input,textarea,[contenteditable]'))return;const files=[...(event.clipboardData?.files??[])].filter(f=>f.type.startsWith('image/'));if(files.length){event.preventDefault();importFiles(files);}};
    const keys=(event:KeyboardEvent)=>{const editable=event.target instanceof HTMLElement&&event.target.closest('input,textarea,select,[contenteditable]');const key=event.key.toLowerCase(),cmd=event.metaKey||event.ctrlKey;if((editable&&!cmd)||dialog)return;
      if(key==='escape'){e.preview=null;e.selection=null;e.setTool('move');e.emit();return;}
      if(cmd){const actions:Record<string,()=>unknown>={z:()=>event.shiftKey?e.redo():e.undo(),y:()=>e.redo(),s:()=>e.saveProject(),o:()=>projectRef.current?.click(),'0':()=>e.view?.fit(),'1':()=>e.view?.zoomTo(1/devicePixelRatio),d:()=>e.setSelection(null),i:()=>event.shiftKey&&e.invertSel(),e:()=>event.shiftKey?e.flattenVisible():e.mergeDown(),j:()=>e.selected&&e.execute([{type:'layer.duplicate',id:e.selected}],'复制图层'),g:()=>event.shiftKey?e.ungroup():e.group(),enter:()=>setDialog('export')};if(actions[key]){event.preventDefault();run(actions[key]);}return;}
      const tool=tools.find(t=>t.key.toLowerCase()===key);if(tool){event.preventDefault();e.setTool(tool.id);}
      else if(key==='delete'||key==='backspace'){if(e.selection&&!e.editingMask&&e.active&&isRaster(e.active)){event.preventDefault();run(()=>e.clearSelectedPixels());}else if(e.selected){event.preventDefault();run(()=>e.editingMask?e.removeMask():e.execute([{type:'layer.remove',id:e.selected!}],'删除图层'));}}
      else if(key==='x'){event.preventDefault();e.swapColors();}
      else if(key==='d'){event.preventDefault();e.resetColors();}
      else if(key==='['||key===']'){e.brush.radius=Math.max(1,Math.min(200,e.brush.radius+(key==='['?-4:4)));e.emit();}
      else if(key==='enter'&&e.tool==='crop')run(()=>e.crop());
      else if(key.startsWith('arrow')&&e.active){event.preventDefault();const amount=event.shiftKey?10:1;run(()=>e.patch({x:e.active!.x+(key==='arrowright'?amount:key==='arrowleft'?-amount:0),y:e.active!.y+(key==='arrowdown'?amount:key==='arrowup'?-amount:0)}));}
    };
    document.addEventListener('paste',paste);document.addEventListener('keydown',keys);return()=>{document.removeEventListener('paste',paste);document.removeEventListener('keydown',keys);};
  });
  const layer=e.active,raster=layer&&isRaster(layer)?layer:null,loc=layer?locateNode(e.doc,layer.id):null,busy=e.busy||!e.ready||e.store.busy,brushTool=['brush','erase'].includes(e.tool),floodTool=['wand','fill'].includes(e.tool),selBox=e.selection&&selectionBounds(e.selection);
  const status={loading:'正在恢复',saving:'正在保存…',saved:'已在此浏览器保存',error:'自动保存失败',disabled:'请下载工程备份'}[e.saveState];
  return <main className={`app ${drop?'is-dropping':''}`} onDragOver={event=>{if(event.dataTransfer.types.includes('Files')){event.preventDefault();setDrop(true);}}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDrop(false);}} onDrop={event=>{if(event.dataTransfer.files.length){event.preventDefault();setDrop(false);importFiles([...event.dataTransfer.files]);}}}>
    <header className="topbar">
      <div className="brand"><Stack weight="duotone" size={25}/><span>lite <b>ps</b></span></div>
      <div className="header-actions"><button onClick={()=>setDialog('new')} disabled={busy}><FilePlus size={17}/><span>新建</span></button><button onClick={()=>projectRef.current?.click()} disabled={busy}><FolderOpen size={17}/><span>打开</span></button><button onClick={()=>fileRef.current?.click()} disabled={busy}><Plus size={17}/><span>添加图片</span></button></div>
      <div className="header-spacer"/>{e.hostConnection&&<button className="connection-button" onClick={()=>e.hostConnection?.disconnect()} title={e.hostConnection.origin}>已连接 · 断开</button>}
      <button className="save-project" onClick={()=>run(()=>e.saveProject())} disabled={busy}><DownloadSimple size={17}/><span>保存工程</span></button>
      <button className="primary export-button" onClick={()=>setDialog('export')} disabled={busy}><UploadSimple size={17}/><span>导出</span></button>
    </header>
    <div className="contextbar">
      <div className="history-controls"><ToolButton icon={ArrowUUpLeft} label={`撤销${e.store.undoLabel?' · '+e.store.undoLabel:''} (⌘Z)`} onClick={()=>run(()=>e.undo())} disabled={!e.store.canUndo||busy}/><ToolButton icon={ArrowUUpRight} label="重做 (⌘⇧Z)" onClick={()=>run(()=>e.redo())} disabled={!e.store.canRedo||busy}/></div>
      <span className="tool-name">{tools.find(t=>t.id===e.tool)?.name}</span>
      {e.editingMask&&<span className="tool-hint">图层蒙版 · 黑藏白显 · X 切换前后景色 · D 恢复黑白 · 点图层缩略图回像素 · Shift 点蒙版停用</span>}
      {brushTool?<div className="brush-options"><label>大小 <input aria-label="笔刷半径" type="number" min={1} max={200} value={e.brush.radius} onChange={event=>{e.brush.radius=Math.max(1,Math.min(200,+event.target.value));e.emit();}}/><span>px</span></label><label>硬度 <RangeSlider className="be-slider h-7" aria-label="笔刷硬度" min={0} max={100} step={1} value={e.brush.hardness*100} showTicks={false} formatValueText={n=>`${Math.round(n)}`} onValueChange={next=>{e.brush.hardness=next/100;e.emit();}}/></label>{e.tool==='brush'?<input type="color" aria-label="画笔颜色" value={e.brush.color} onChange={event=>{e.brush.color=event.target.value;e.emit();}}/>:<button className={e.brush.restore?'selected-option':''} onClick={()=>{e.brush.restore=!e.brush.restore;e.emit();}}>{e.tool==='erase'?'恢复擦除':'减去区域'}<span className="toggle-dot"/></button>}</div>:floodTool?<div className="brush-options"><label>容差 <input aria-label="容差" type="number" min={0} max={255} value={e.selectOpts.tolerance} onChange={event=>{e.selectOpts.tolerance=Math.max(0,Math.min(255,+event.target.value||0));e.emit();}}/></label><button className={e.selectOpts.contiguous?'selected-option':''} onClick={()=>{e.selectOpts.contiguous=!e.selectOpts.contiguous;e.emit();}}>{e.selectOpts.contiguous?'连续':'不连续'}<span className="toggle-dot"/></button></div>:e.tool==='crop'?<div className="inline-options"><span>拖出范围，按 Enter 裁切</span><button disabled={!selBox||busy} onClick={()=>run(()=>e.crop())}><Check size={15}/>应用裁切</button></div>:<span className="tool-hint">{e.editingMask?'':e.tool==='move'?'拖动图层 · Shift 辅助变换':e.tool==='hand'?'拖动画布 · 按住空格临时平移':e.tool==='select'?'拖出选区 · Delete 删像素 · ⌘⇧I 反选 · 加蒙版即选区变蒙版':e.tool==='lasso'?'拖一圈闭合 · Shift 加选 · Alt 减选':e.tool==='eyedropper'?'点击画布取色':''}</span>}
      <div className="header-spacer"/>{e.selection&&<><button className="clear-selection" onClick={()=>e.invertSel()}>反选</button><button className="clear-selection" disabled={!layer||!!layer.mask||busy} onClick={()=>run(()=>e.addMask())}>选区变蒙版</button><button className="clear-selection" onClick={()=>e.setSelection(null)}><X size={14}/>取消选区</button></>}
    </div>
    <div className="workspace">
      <nav className="tools" aria-label="编辑工具">{tools.map(t=><ToolButton key={t.id} icon={t.icon} label={`${t.name} (${t.key})`} active={e.tool===t.id} disabled={busy} onClick={()=>e.setTool(t.id)}/>)}<div className="tool-divider"/><div className="color-wells"><label className="color-chip color-bg" title="背景色"><input type="color" aria-label="背景色" value={e.brush.background} onChange={event=>{e.brush.background=event.target.value;e.emit();}}/></label><label className="color-chip color-fg" title="前景色"><input type="color" aria-label="前景色" value={e.brush.color} onChange={event=>{e.brush.color=event.target.value;e.emit();}}/></label><button type="button" className="color-swap" title="切换前景色和背景色 (X)" aria-label="切换前景色和背景色 (X)" onClick={()=>e.swapColors()}><ArrowsClockwise size={11}/></button></div><div className="tools-spacer"/><ToolButton icon={Info} label="使用帮助" onClick={()=>setDialog('help')}/></nav>
      <section className="canvas-area" aria-label="编辑画布">
        <div className="document-tab"><span className="document-dot"/><input aria-label="工程名称" key={e.doc.id} defaultValue={e.doc.name} onBlur={event=>{const name=event.target.value.trim().slice(0,100)||'未命名';run(()=>e.execute([{type:'document.rename',name}],'工程名称'));}}/><span>{e.doc.width} × {e.doc.height}</span><span className="save-state" data-state={e.saveState}>{e.saveState==='saved'&&<Check size={12}/>} {status}</span></div>
        <div className="viewport" ref={host}><div className="artboard" ref={board}/><canvas ref={canvas} aria-label="图层编辑画布"/><canvas className="overlay" ref={overlay}/>
          {!e.doc.layers.length&&e.ready&&<div className="empty-state"><div className="empty-icon"><Image size={32} weight="thin"/></div><h1>把图片放进来，开始编辑</h1><p>拖入图片，或直接粘贴</p><button className="empty-import" onClick={()=>fileRef.current?.click()}><Plus size={17}/>选择图片</button><button className="text-button" onClick={()=>run(()=>e.example())}>用示例试一试 <span>↗</span></button><small>PNG、JPEG、WebP · 图片在本机处理</small></div>}
        </div>
        <footer className="canvas-status"><span>{selBox?`选区 ${Math.round(selBox.width)} × ${Math.round(selBox.height)}`:`${nodeCount(e.doc)} 个图层`}</span><span className="status-hint">空格拖动 · ⌘ / Ctrl + 滚轮缩放</span><div className="zoom-controls"><ToolButton icon={MagnifyingGlassMinus} label="缩小" onClick={()=>e.view?.zoomTo(e.zoom/1.25)}/><button className="zoom-value" onClick={()=>e.view?.zoomTo(1/devicePixelRatio)} title="100% 物理像素">{Math.round(e.zoom*devicePixelRatio*100)}%</button><ToolButton icon={MagnifyingGlassPlus} label="放大" onClick={()=>e.view?.zoomTo(e.zoom*1.25)}/><ToolButton icon={ArrowsOut} label="适合窗口 (⌘0)" onClick={()=>e.view?.fit()}/></div></footer>
      </section>
      <aside className="inspector" aria-label="图层和属性">
        <section className="layers-section"><div className="section-title"><h2>图层 <span>{nodeCount(e.doc)}</span></h2><div><ToolButton icon={Plus} label="添加空白图层" onClick={()=>run(()=>e.addBlank())} disabled={busy}/><ToolButton icon={FolderPlus} label="编组 (⌘G)" onClick={()=>run(()=>e.group())} disabled={busy}/><ToolButton icon={FolderMinus} label="解散组 (⌘⇧G)" onClick={()=>run(()=>e.ungroup())} disabled={!layer||!isGroup(layer)||layer.locked||busy}/><ToolButton icon={Trash} label={e.editingMask?'删除图层蒙版':'删除图层'} onClick={()=>run(()=>e.editingMask?e.removeMask():e.selected&&e.execute([{type:'layer.remove',id:e.selected}],'删除图层'))} disabled={!layer||layer.locked||busy}/></div></div>
          <div className="blend-controls"><select aria-label="混合模式" disabled={!layer||layer.locked||busy} value={layer?.blend??'source-over'} onChange={event=>run(()=>e.patch({blend:event.target.value as GroupBlend}))}>{layer&&isGroup(layer)&&<option value={GROUP_BLEND}>穿透</option>}{BLENDS.map((b,i)=><option value={b} key={b}>{blendNames[i]}</option>)}</select>{layer?<Adjust editor={e} label="不透明度" property="opacity" min={0}/>:<span className="muted">100%</span>}</div>
          <div className="layer-list" role="list" aria-label="图层列表"><LayerTree nodes={e.doc.layers} parentId={null} depth={0} e={e} busy={busy} dragLayer={dragLayer} setDragLayer={setDragLayer} run={run}/>{!e.doc.layers.length&&<div className="no-layers"><Stack size={26} weight="thin"/><p>添加图片后，图层会出现在这里</p></div>}</div>
          <div className="layer-footer"><span>拖动调整顺序</span><ToolButton icon={Circle} label={e.selection?'选区变蒙版':'添加图层蒙版'} disabled={!layer||layer.locked||busy||!!layer.mask} onClick={()=>run(()=>e.addMask())}/><ToolButton icon={Stack} label="向下合并 (⌘E)" disabled={!loc||loc.index===0||!layer||layer.locked||loc.siblings[loc.index-1].locked||busy} onClick={()=>run(()=>e.mergeDown())}/><ToolButton icon={Image} label="拼合可见 (⌘⇧E)" disabled={!e.doc.layers.length||busy} onClick={()=>run(()=>e.flattenVisible())}/><ToolButton icon={ArrowUp} label="图层上移" disabled={!loc||!layer||layer.locked||busy||loc.index===loc.siblings.length-1} onClick={()=>run(()=>layer&&loc&&e.execute([{type:'layer.reorder',id:layer.id,index:loc.index+1,parentId:loc.parent?.id??null}],'图层上移'))}/><ToolButton icon={ArrowDown} label="图层下移" disabled={!loc||!layer||layer.locked||busy||loc.index===0} onClick={()=>run(()=>layer&&loc&&e.execute([{type:'layer.reorder',id:layer.id,index:loc.index-1,parentId:loc.parent?.id??null}],'图层下移'))}/><ToolButton icon={Copy} label="复制图层 (⌘J)" disabled={!layer||layer.locked||busy} onClick={()=>run(()=>layer&&e.execute([{type:'layer.duplicate',id:layer.id}],'复制图层'))}/></div>
        </section>
        <section className="properties"><div className="section-title"><h2><SlidersHorizontal size={15}/>属性</h2>{layer?.locked&&<span className="lock-note"><LockSimple size={12}/>已锁定</span>}</div>{raster?<fieldset disabled={raster.locked||busy}>
          <label className="rename-field"><span>名称</span><input aria-label="图层名称" key={raster.id+raster.name} defaultValue={raster.name} onBlur={event=>run(()=>e.patch({name:event.target.value.trim().slice(0,100)||'图层'}))}/></label>
          <h3>变换</h3><div className="number-grid"><NumberField label="X" value={raster.x} onChange={x=>run(()=>e.patch({x}))}/><NumberField label="Y" value={raster.y} onChange={y=>run(()=>e.patch({y}))}/><NumberField label="宽" value={raster.width*raster.scaleX} min={1} onChange={v=>run(()=>e.patch({scaleX:v/raster.width}))}/><NumberField label="高" value={raster.height*raster.scaleY} min={1} onChange={v=>run(()=>e.patch({scaleY:v/raster.height}))}/></div><div className="rotation-row"><NumberField label="角度" value={raster.rotation} onChange={rotation=>run(()=>e.patch({rotation}))}/><ToolButton icon={ArrowsHorizontal} label="水平翻转" active={raster.flipX} onClick={()=>run(()=>e.patch({flipX:!raster.flipX}))}/><ToolButton icon={ArrowsVertical} label="垂直翻转" active={raster.flipY} onClick={()=>run(()=>e.patch({flipY:!raster.flipY}))}/></div>
          <div className="adjust-title"><h3>色彩调整</h3><button onClick={()=>run(()=>e.patch({brightness:0,contrast:0,saturation:0}))} title="重置色彩调整"><ArrowsClockwise size={13}/>重置</button></div><Adjust editor={e} label="亮度" property="brightness"/><Adjust editor={e} label="对比度" property="contrast"/><Adjust editor={e} label="饱和度" property="saturation"/>
        </fieldset>:layer&&isGroup(layer)?<fieldset disabled={layer.locked||busy}>
          <label className="rename-field"><span>名称</span><input aria-label="组名称" key={layer.id+layer.name} defaultValue={layer.name} onBlur={event=>run(()=>e.patch({name:event.target.value.trim().slice(0,100)||'组'}))}/></label>
          <h3>组变换</h3><div className="number-grid"><NumberField label="X" value={layer.x} onChange={x=>run(()=>e.patch({x}))}/><NumberField label="Y" value={layer.y} onChange={y=>run(()=>e.patch({y}))}/><NumberField label="缩放X" value={layer.scaleX} min={.001} step={.01} onChange={scaleX=>run(()=>e.patch({scaleX}))}/><NumberField label="缩放Y" value={layer.scaleY} min={.001} step={.01} onChange={scaleY=>run(()=>e.patch({scaleY}))}/></div><div className="rotation-row"><NumberField label="角度" value={layer.rotation} onChange={rotation=>run(()=>e.patch({rotation}))}/><ToolButton icon={ArrowsHorizontal} label="水平翻转" active={layer.flipX} onClick={()=>run(()=>e.patch({flipX:!layer.flipX}))}/><ToolButton icon={ArrowsVertical} label="垂直翻转" active={layer.flipY} onClick={()=>run(()=>e.patch({flipY:!layer.flipY}))}/></div>
        </fieldset>:<div className="property-empty"><Cursor size={22} weight="thin"/><p>选择一个图层<br/>查看与调整它的属性</p></div>}
        </section>
        <div className="local-note"><span className="local-dot"/>在浏览器本地处理 <span>v0.1</span></div>
      </aside>
    </div>
    {drop&&<div className="drop-zone"><UploadSimple size={42}/><p>松开以添加图片或打开工程</p></div>}
    {e.hostRequest&&<div className="connection-request" role="alert"><strong>允许连接当前工程？</strong><p>{e.hostRequest.origin}</p><span>连接后，对方可以读取图片、修改图层并导出结果。</span><div><button onClick={()=>e.hostRequest?.reject()}>拒绝</button><button className="primary" onClick={()=>e.hostRequest?.accept()}>允许连接</button></div></div>}
    {e.message&&<div className={`toast ${e.messageKind}`} role={e.messageKind==='error'?'alert':'status'}>{e.messageKind==='error'?<Info size={17}/>:<Check size={17}/>}<span>{e.message}</span><button aria-label="关闭通知" onClick={()=>{e.message='';e.emit();}}><X size={15}/></button></div>}
    {e.busy&&<div className="busy-indicator" role="status"><span/>正在处理…</div>}
    <input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={event=>{importFiles([...event.target.files??[]]);event.target.value='';}}/>
    <input ref={projectRef} hidden type="file" accept=".lightps" onChange={event=>{if(event.target.files?.[0])importFiles([event.target.files[0]]);event.target.value='';}}/>
    <dialog ref={dialogRef} onCancel={()=>setDialog(null)} onClick={event=>{if(event.target===dialogRef.current)setDialog(null);}}>
      <div className="dialog-content"><div className="dialog-heading"><h2>{dialog==='new'?'新建画布':dialog==='export'?'导出图片':'随手编辑，轻松带走'}</h2><ToolButton icon={X} label="关闭对话框" onClick={()=>setDialog(null)}/></div>
      {dialog==='new'&&<form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(replaceOK())run(()=>{e.newDocument(+data.get('width')!,+data.get('height')!,String(data.get('name')||'未命名'));setDialog(null);});}}><label className="form-label">工程名称<input name="name" defaultValue="未命名" maxLength={100} autoFocus/></label><div className="form-grid"><label className="form-label">宽度 · px<input name="width" type="number" min={1} max={LIMITS.side} defaultValue={1600} required/></label><label className="form-label">高度 · px<input name="height" type="number" min={1} max={LIMITS.side} defaultValue={1200} required/></label></div><p className="dialog-note">透明背景 · 最大 4096 × 4096 像素</p><button className="primary dialog-primary" type="submit">创建画布</button></form>}
      {dialog==='export'&&<div><p className="export-dimensions">{e.doc.width} × {e.doc.height}<span>原始画布尺寸</span></p><label className="form-label">图片格式<select value={format} onChange={event=>setFormat(event.target.value)}><option value="image/png">PNG · 保留透明背景</option><option value="image/jpeg">JPEG · 白色背景</option><option value="image/webp">WebP · 更小的文件</option></select></label><button className="primary dialog-primary" onClick={()=>run(async()=>{await e.downloadImage(format);setDialog(null);})}><DownloadSimple size={17}/>下载图片</button><div className="export-secondary"><button onClick={()=>run(()=>e.copyImage())}><Copy size={16}/>复制图片</button></div><p className="dialog-note">保留图层以便下次修改，请使用“保存工程”。</p></div>}
      {dialog==='help'&&<div className="help-content"><p>拖入、粘贴或添加图片。每张图片作为独立图层，所有处理都在当前浏览器完成。</p><dl><dt>移动 / 缩放 / 旋转</dt><dd>V · 拖动图层与控制点</dd><dt>平移 / 缩放视口</dt><dd>空格拖动 · ⌘ / Ctrl + 滚轮</dd><dt>撤销 / 重做</dt><dd>⌘Z / ⌘⇧Z（Windows 使用 Ctrl）</dd><dt>适合窗口 / 原始像素</dt><dd>⌘0 / ⌘1</dd><dt>选区 / 套索 / 魔棒 / 油漆桶</dt><dd>M / L / W / G · 套索拖一圈闭合 · Delete 删选区像素 · ⌘⇧I 反选 · 有选区时加蒙版即选区变蒙版 · Shift 加选 · Alt 减选</dd><dt>向下合并 / 拼合可见</dt><dd>⌘E / ⌘⇧E</dd><dt>画笔 / 擦除</dt><dd>B / E · [ ] 调笔刷大小</dd><dt>前景色 / 背景色</dt><dd>X 互换 · D 恢复黑白 · 画笔用前景色</dd><dt>图层蒙版</dt><dd>图层列表底部圆点添加 · 点蒙版缩略图后画黑藏白显 · X 切换黑白 · Shift 点停用 · Delete 删蒙版</dd><dt>保存工程 / 导出图片</dt><dd>⌘S / ⌘Enter</dd></dl><p>擦除可切换为“恢复擦除”。自动保存仅保存在此浏览器，请下载 .lightps 工程作为备份。</p><p className="dialog-note">首版支持基础位图编辑；暂不支持 PSD、文字排版及专用平台插件。</p></div>}
      </div>
    </dialog>
  </main>;
}
